#Project Euler

#Problem #2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

list_nums = [0, 1]

a = -1
b = 0

while list_nums[-1] <4000000:

	a += 1
	b += 1
	
	sum = list_nums[a] + list_nums[b]
	list_nums.append(sum)
	
print "\nFibonacci Series\n", list_nums, "\n"

new_list_nums = []

for x in list_nums:
	if x % 2 == 0:
		new_list_nums.append(x)
print "\nEven Fibonacci Numbers:\n", new_list_nums

sum_num = 0

for z in new_list_nums:
	sum_num = sum_num + z
print "\nSum of Even Fibonacci Numbers:\n", sum_num, "\n"